# Generated by Django 3.2.11 on 2022-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('actual_url', models.TextField()),
                ('shorten_url', models.CharField(max_length=100)),
            ],
        ),
    ]
