# Generated by Django 3.2.11 on 2022-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='actual_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='shorten_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
