# Generated by Django 3.2.11 on 2022-02-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlGenerator', '0002_auto_20220203_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
