# Generated by Django 3.2.12 on 2022-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlGenerator', '0008_alter_link_actual_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='actual_url',
        ),
        migrations.AddField(
            model_name='link',
            name='hit_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
