# Generated by Django 3.2.12 on 2022-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlGenerator', '0009_auto_20220215_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='actual_url',
            field=models.TextField(default=''),
        ),
    ]
