# Generated by Django 3.2.12 on 2022-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlGenerator', '0010_link_actual_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hit_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
